security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        # Define a custom user provider to load users from the database
        database_users:
            entity:
                class: App\Entity\User
                property: emailAdress # Change this to the property you use as the username
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: emailAdress
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            # Use the custom user provider to authenticate users
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_vu_user_index
                enable_csrf: true
            logout:
                path: app_logout
                # where to redirect after logout
                target: app_login

            # Add authentication mechanisms as needed (e.g., form_login, guard, etc.)

    # Access control rules

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
